questions = {
    "What is the capital of Nepal?": "Kathmandu",
    "What is the largest mammal in the world?": "Blue Whale",
    "Who painted the Mona Lisa?": "Leonardo da Vinci",
    "What is the chemical symbol for water?": "H2O",
    "How many continents are there?": "7",
    "Which planet is known as the Red Planet?": "Mars",
    "What is the tallest mountain in the world?": "Mount Everest",
    "Who was the first man to step on the moon?": "Neil Armstrong",
    "What is the largest organ in the human body?": "Skin",
    "What is the powerhouse of the cell?": "Mitochondria",
    "Who wrote 'Romeo and Juliet'?": "William Shakespeare",
    "What is the closest planet to the Sun?": "Mercury",
    "Who discovered penicillin?": "Alexander Fleming",
    "What is the capital of Japan?": "Tokyo",
    "Which famous scientist developed the theory of relativity?": "Albert Einstein",
    "What is the chemical symbol for gold?": "Au",
    "What year did the Titanic sink?": "1912",
    "Who is known as the 'Father of Computers'?": "Charles Babbage",
    "What is the process by which plants make their own food called?": "Photosynthesis",
    "What is the main ingredient in guacamole?": "Avocado",
    "Who painted the ceiling of the Sistine Chapel?": "Michelangelo",
    "What is the capital of Australia?": "Canberra",
    "Who wrote 'To Kill a Mockingbird'?": "Harper Lee",
    "What is the chemical symbol for iron?": "Fe",
    "What is the largest ocean on Earth?": "Pacific Ocean",
    "Who is the author of 'The Great Gatsby'?": "F. Scott Fitzgerald",
    "What is the currency of Russia?": "Russian Ruble",
    "Which gas do plants use for photosynthesis?": "Carbon dioxide",
    "Who invented the telephone?": "Alexander Graham Bell",
    "What is the largest organ in the human body?": "Liver",
    "What is the chemical symbol for sodium?": "Na",
    "What symbol represents the Python language?": "Py",
"What does the function print() do in Python?": "Prints output to the console",
"How do you start a single-line comment in Python?": "#",
"What is the keyword used to define a function in Python?": "def",
"What does the import statement do in Python?": "Imports modules or packages",
"What symbol is used for floor division in Python?": "//",
"What function is used to get the length of a string in Python?": "len()",
"What is the purpose of the break statement in Python?": "To exit a loop prematurely",
"What type of data structure is a list in Python?": "Ordered and mutable",
"What does the range() function return in Python?": "A sequence of numbers",
"How do you access the last element of a list in Python?": "list_name[-1]",
"What does the strip() method do for strings in Python?": "Removes leading and trailing whitespace",
"What is the output of 3**2 in Python?": "9",
"What is the purpose of the pass statement in Python?": "To do nothing",
"What symbol is used for exponentiation in Python?": "**",
"What is the output of 5 // 2 in Python?": "2",
"What function is used to convert a string to lowercase in Python?": "lower()",
"What is the purpose of the continue statement in Python?": "To skip the rest of the loop iteration and start from the beginning",
"What is the output of 'hello' + 'world' in Python?": "'helloworld'",
"What function is used to convert a string to uppercase in Python?": "upper()",
"What does the input() function do in Python?": "Accepts user input",
"What is the output of 4 % 2 in Python?": "0",
"What is the keyword used for conditional statements in Python?": "if",
"What does the append() method do for lists in Python?": "Adds an element to the end of the list",
"What does the pop() method do for lists in Python?": "Removes and returns the last element of the list",
"What symbol is used to denote a comment that spans multiple lines in Python?": "Triple quotes (""",
"What is the output of len('python') in Python?": "6",
"What is the output of bool(0) in Python?": "False",
"What is the output of bool('False') in Python?": "True",
"What does the del statement do in Python?": "Deletes a reference to an object",
"What does the insert() method do for lists in Python?": "Inserts an element at a specified position",
"What is the output of 3 == 3.0 in Python?": "True",
"What is the output of not True in Python?": "False",
"What does the extend() method do for lists in Python?": "Appends elements from another list to the current list",
"What is the output of 2 * 3 ** 2 in Python?": "18",
"What does the find() method do for strings in Python?": "Returns the lowest index where the substring is found",
"What is the output of 4 < 5 and 5 < 6 in Python?": "True",
"What does the replace() method do for strings in Python?": "Replaces occurrences of a substring with another substring",
"What is the output of list(range(3)) in Python?": "[0, 1, 2]",
"What does the sort() method do for lists in Python?": "Sorts the list in ascending order",
"What is the output of sum([1, 2, 3]) in Python?": "6",
"What is the output of 3 != 4 in Python?": "True",
"What does the reverse() method do for lists in Python?": "Reverses the order of elements in the list",
"What is the output of min(1, 2, 3) in Python?": "1",
"What is the output of max(4, 5, 6) in Python?": "6",
"What is the output of sorted([3, 1, 2]) in Python?": "[1, 2, 3]",
"What does the split() method do for strings in Python?": "Splits the string into a list of substrings",
"What is the output of abs(-5) in Python?": "5",
"What is the output of type(5) in Python?": "<class 'int'>",
"What is the output of bin(5) in Python?": "'0b101'",
"What is Flutter?": "A UI toolkit developed by Google for building natively compiled applications for mobile, web, and desktop from a single codebase.",
"Which programming language is primarily used for developing Flutter applications?": "Dart",
"What is the main advantage of Flutter over other cross-platform frameworks?": "Hot reload feature for instant code changes",
"What is the root widget of a Flutter application?": "MaterialApp or CupertinoApp",
"What command is used to create a new Flutter project?": "flutter create",
"What is the purpose of the pubspec.yaml file in a Flutter project?": "To define project dependencies and metadata",
"Which widget is used to create a clickable button in Flutter?": "ElevatedButton or TextButton",
"What is the widget used to create a scrollable list of widgets in Flutter?": "ListView",
"What widget is used to display images in Flutter?": "Image",
"What command is used to run a Flutter app?": "flutter run",
"What widget is used to arrange widgets linearly in Flutter?": "Row or Column",
"What does the setState() function do in Flutter?": "Notifies the framework that the internal state of the object has changed, triggering a rebuild of the UI.",
"What is the purpose of the BuildContext parameter in Flutter widgets?": "To provide access to information about the widget's location in the widget tree.",
"What is a Flutter widget tree?": "A hierarchical structure of widgets that Flutter uses to render the user interface.",
"What is the purpose of the Expanded widget in Flutter?": "To allow a child widget of a Row, Column, or Flex to expand to fill the available space.",
"What widget is used to add padding around other widgets in Flutter?": "Padding",
"What is the purpose of the Scaffold widget in Flutter?": "To implement the basic material design visual layout structure.",
"What is the purpose of the Container widget in Flutter?": "To create a rectangular visual element that can be decorated with a BoxDecoration.",
"What is Flutter's equivalent of CSS for styling widgets?": "Flutter uses a combination of properties like color, font size, padding, etc., along with BoxDecoration and BoxDecoration to style widgets.",
"What is the purpose of the FutureBuilder widget in Flutter?": "To build a widget tree based on the latest snapshot of interaction with a Future.",
"What widget is used to create a bottom navigation bar in Flutter?": "BottomNavigationBar",
"What widget is used to create tabs in Flutter?": "TabBar",
"What is the purpose of the PageRoute widget in Flutter?": "To define routes for navigating between screens.",
"What widget is used to create an animated transition between two widgets in Flutter?": "AnimatedSwitcher",
"What is the purpose of the GestureDetector widget in Flutter?": "To detect gestures made by the user, such as taps, drags, and scrolls.",
"What widget is used to create a circular progress indicator in Flutter?": "CircularProgressIndicator",
"What is the purpose of the Key parameter in Flutter widgets?": "To uniquely identify widgets, enabling Flutter to efficiently update the UI.",
"What widget is used to create a text input field in Flutter?": "TextField",
"What is the purpose of the PageRouteBuilder class in Flutter?": "To build custom page route transitions.",
"What is the purpose of the InkWell widget in Flutter?": "To create a rectangular area of a Material that responds to touch.",
"What is Flutter's solution for responsive design?": "Flutter uses a combination of MediaQuery, LayoutBuilder, and Flex widgets to create responsive layouts.",
"What is the purpose of the ClipRRect widget in Flutter?": "To clip its child using a rounded rectangle.",
"What widget is used to create a tooltip in Flutter?": "Tooltip",
"What is the purpose of the ValueListenableBuilder widget in Flutter?": "To rebuild the UI in response to changes in a ValueListenable.",
"What is the purpose of the AspectRatio widget in Flutter?": "To force a child widget to have a specific aspect ratio.",
"What is the purpose of the IndexedStack widget in Flutter?": "To show only one child from a list of children at a time.",
"What is the purpose of the Positioned widget in Flutter?": "To position a child within a Stack.",
"What widget is used to create a drawer menu in Flutter?": "Drawer",
"What is the purpose of the SingleChildScrollView widget in Flutter?": "To make its child scrollable.",
"What widget is used to create a grid of widgets in Flutter?": "GridView",
"What is the purpose of the ClipOval widget in Flutter?": "To clip its child using an oval shape.",
"What widget is used to create a card with a shadow effect in Flutter?": "Card",
"What is the purpose of the Flexible widget in Flutter?": "To determine how a child of a Row, Column, or Flex should flex to fill the available space.",
"What widget is used to create a dialog box in Flutter?": "AlertDialog",
"What is the purpose of the FittedBox widget in Flutter?": "To automatically size and position its child to fit the parent widget.",
"What widget is used to create a switch in Flutter?": "Switch",
"What is the purpose of the PopupMenuButton widget in Flutter?": "To display a menu when pressed.",
"What widget is used to create a slider in Flutter?": "Slider",
"What is the purpose of the Spacer widget in Flutter?": "To create space between widgets in a Row or Column.",
"What widget is used to create a material design app bar in Flutter?": "AppBar",
"What is the largest animal on Earth?": "Blue whale",
"Which animal is known as the 'king of the jungle' despite not living in jungles?": "Lion",
"What is the fastest land animal?": "Cheetah",
"Which animal has the longest neck?": "Giraffe",
"What is the only mammal capable of sustained flight?": "Bat",
"Which animal is known for its ability to change its color to match its surroundings?": "Chameleon",
"What is the largest species of bear?": "Polar bear",
"Which bird is known for its ability to mimic human speech?": "Parrot",
"What is the largest species of big cat?": "Tiger",
"Which animal is known for its ability to regrow lost limbs?": "Starfish",
"What is the only mammal that can fly backward?": "Hummingbird",
"Which animal has the longest lifespan?": "Bowhead whale",
"What is the tallest animal on land?": "Giraffe",
"Which animal is known for its black and white stripes?": "Zebra",
"What is the largest living reptile?": "Saltwater crocodile",
"Which animal has the largest eyes relative to its body size?": "Colossal squid",
"What is the only mammal that lays eggs?": "Platypus",
"Which animal is known as the 'ship of the desert'?": "Camel",
"What is the largest species of shark?": "Whale shark",
"Which bird is the fastest animal in a dive?": "Peregrine falcon",
"What is the largest living primate?": "Eastern gorilla",
"Which animal is known for its long, sticky tongue used for catching insects?": "Anteater",
"What is the slowest mammal on land?": "Sloth",
"Which animal is known for its ability to mimic the appearance of a twig or leaf?": "Stick insect",
"What is the heaviest bird capable of flight?": "Kori bustard",
"Which animal has the largest brain relative to its body size?": "Sperm whale",
"What is the only mammal that can truly fly (without gliding)?": "Bat",
"Which animal is known as the 'gentle giant' of the ocean?": "Whale shark",
"What is the largest living species of turtle?": "Leatherback sea turtle",
"Which animal has the longest migration route of any mammal?": "Arctic tern",
"What is the smallest mammal in the world?": "Bumblebee bat",
"Which animal is known for its ability to mimic human laughter?": "Hyena",
"What is the fastest marine animal?": "Sailfish",
"Which bird is known for its courtship dance?": "Peacock",
"What is the largest species of kangaroo?": "Red kangaroo",
"Which animal has the longest hibernation period?": "European hedgehog",
"What is the largest species of lizard?": "Komodo dragon",
"Which animal is known as the 'king of the skies'?": "Bald eagle",
"What is the only marsupial native to North America?": "Virginia opossum",
"Which animal is known for its ability to change color based on its mood and surroundings?": "Cuttlefish",
"What is the largest species of penguin?": "Emperor penguin",
"Which animal has the most teeth?": "Snail",
"What is the only mammal that can survive in Antarctica year-round?": "Weddell seal",
"Which animal is known for its ability to climb trees and hang upside down?": "Sloth",
"What is the fastest animal in the ocean?": "Sailfish",
"Which animal has the longest migration route of any land animal?": "Wildebeest",
"What is the largest species of eagle?": "Harpy eagle",
"Which animal is known as the 'giant panda'?": "Panda",
"What is the smallest species of monkey?": "Pygmy marmoset",
"Which animal is known for its ability to change the color of its skin to blend in with its surroundings?": "Octopus"
}